### ISSUE TITLE
Handle xdata field like crossref field

### ISSUE THREAD

**Issue by adamliter** [ge-ne/bibtool#10]
Biblatex provides a data field called `xdata`, which is like `crossref` in that it inherits data from some other entry but unlike `crossref` in that the semantics are not that of a parent-child relationship.

At any rate, it would be nice if the `xdata` field were treated liked `crossref` in that you could declare

    select.crossrefs = on

and have BibTool follow `xdata` references for the purposes of stuff like key generation, for example, since it is a field designed for inheriting data.

I'm not sure if it would make more sense to have a separate option (something like `select.xdata`) or to have them both controlled by the same option (`select.crossrefs`).

**Comment by ge-ne** [comment]
Properly supporting xdata is more like making it an alias for crossref.

- xdata may take several keys separated by comma
- xdata should be taken into account when selecting

select.crossrefs is a boolean resource. It can not be extended to support xdata without breaking backward compatibility...

I wil think about it (and try to understand the semantics oc xdata and xref)

**Comment by adamliter** [comment]
Making it an alias for crossref would probably work. I'm not sure that much would hinge on the different semantics, at least not for the purposes of BibTool. The different semantics are mostly relevant for when you're actually printing a bibliography, I think. But I also might not understand the difference in their semantics completely myself. :wink:

**Comment by adamliter** [comment]
Here's a bit more information about how this works in Biblatex. I honestly don't know as much about how this works in BibTeX.

Buy anyway, the `crossref` functionality of Biblatex allows for "smart" inheritance of certain fields. All of the inheritance rules are declared starting on line 1588 of [`biblatex.def`](https://github.com/plk/biblatex/blob/master/tex/latex/biblatex/biblatex.def#L1588). They are also discussed in Appendix B of the [Biblatex documentation](http://texdoc.net/texmf-dist/doc/latex/biblatex/biblatex.pdf).

Basically, when a field is inherited using `crossref` (but **not** `xdata`), then the name of the field may change. For example, if you had an `@mvbook` entry with an `author` data field and you `crossref`ed this `@mvbook` entry in an `@inbook` entry, the `author` field would be inherited as `bookauthor`, **not** `author`. On the other hand, if you you used the `xdata` data field to reference the `@mvbook` field it would be inherited as `author`, **not** `bookauthor`.

So basically, `xdata` preserves the name of the data field when used to reference another entry, whereas `crossref` **may or may not** change the name of the data field.

The complete list of "smart" inheritance rules is given in the source file (`biblatex.def`) or can be read in the table in Appendix B of the documentation.

So in order to support this, BibTool would need to be aware of the `crossref` inheritance rules and then just treat `xdata` like it currently treats `crossref` (I assume; that is, I'm assuming that BibTeX doesn't do this sort of "smart" inheritance thing, right? I honestly don't know).

**Comment by ge-ne** [comment]
I have read a little bit myself. I have came to the conclusion that the following changes would be required in BibTool

- a new resource is required to control the inclusion of entries via xdata when selecting. Default: off
- a new resource is required to controll the expansion via xdata. Default: off
- the parser of the xdata field needs to be capable to deal with lists of keys instead of a single key as in crossref
- a new resource is required to controll the rewriting of field names during the expansion of crossref. Default: off
- a new resource is required to add field name mappings. Default: no mappings
- a resource would be nice to clean the field name mappings
- a library could be added to contain the default biber field name mappings
- add field renaming during expansion

That's quite a piece of work. I don't know, whether the definition of the mapping should be deferred until the 3.0 resource language is in place.

**Comment by adamliter** [comment]
That sounds like it would cover things. I'm not too familiar with the actual internals of BibTool, so I'm not sure that I have much to say in terms of implementation and when it makes sense to do things. But your list of things that would need to be done sounds like it would cover it to me. :smile_cat:

**Comment by ge-ne** [comment]
Feature included in 2.64

**Comment by adamliter** [comment]
Thanks! :+1:
