### ISSUE TITLE
BibLaTeX entries

### ISSUE THREAD

**Issue by artemklevtsov** [ge-ne/bibtool#2]
Hi.

Seems biblatex entries not supported. I get message:

``` bash
@Online{RProject,
_^
*** BibTool ERROR:  (line 127 in ./bibs/en-online.bib): Unknown entry type

*** BibTool WARNING: Skiping to next '@'
```

Bibtex support only a misc entry for this. I can't use `new.field.type { misc = online}` because I use misc for other cases. 

Thx.

**Comment by Dellu** [comment]
I am getting the same error for **Collection** entry.

**Comment by ge-ne** [comment]
Which version of BibTool are you running (see bibtool -h)?

**Comment by Dellu** [comment]
2.65

**Comment by ge-ne** [comment]
According to the changelog this bug had been fixed with 2.66.

**Comment by Dellu** [comment]
oh, ok--thanks. I will update

**Comment by mranvick** [comment]
I am running BibTool in version 2.67 installed through homebrew (brew install bib-tool).

I use the following ```toto.bib``` file:

```
@Online{tata,
	author = {titi}
}
```

Running ```bibtool toto.tex``` yields the following:

```
@Online{tata,
_^
*** BibTool ERROR:  (line 1 in ./toto.bib): Unknown entry type

*** BibTool WARNING: Skipping to next '@'
```

I thought this bug was supposed to be solved, did I do anything wrong ?

**Note:** if I run ```bibtool -r biblatex toto.bib ``` I do not have any error message, bus shouldn't it be the default behaviour ?

**Comment by ge-ne** [comment]
Your example shows the intended behaviour and not any bug.

BibLaTeX is _not_ the default. BibTeX(0.99c) is the default. I will not change this -- at least not in BibTool 2.* since it is documented this way.

If you want to change the behaviour for you put a resource{biblatex} instruction into $HOME/.bibtoolrsc

**Comment by mranvick** [comment]
Ok, ok, thanks for the explanation !
