### ISSUE TITLE
please provide the upstream source balls in different compressed formats

### ISSUE THREAD

**Issue by jgmbenoit** [ge-ne/bibtool#22]
Please provide the upstream source balls in more compressed  formats as bz2 and  xz besides gz .

**Comment by ge-ne** [comment]
Why? tgz can be read widely. On my web site I have a zip ball for each distribution -- even though currently not reachable via a  link. Nobody complained that it is missing...

**Comment by jgmbenoit** [comment]
Having tgz and zip is fine, having  tar.bz2 is even better, and tar.xz is kind of extra. The rational behind my request is to save bandwidth and space. In the same vein, I have just noticed that owner and the group of the files in the tarball are gene and gene, respectively. I would be better if they were root and root, respectively.  On Debian based boxes, the mk-origtargz utility applies the arguments --owner=root', '--group=root', '--mode=a+rX'; this can be set via the environment variable TAR_OPTIONS I guess. (A good idea would be also to sort the file to facilitate comparison between tarball contents.) I am asking because the current Debian repackagiing utility only removes the undesirable files from the original tarball itself: having a tar.bz2 (or tar.xz) may save space and bandwith for distribution in general.

**Comment by ge-ne** [comment]
Well providing additional archive formats would increase space requirements and bandwidth for _my_ web server. Here I am a little bit selfish.

Thanks for pointing me to the owner and group. I will adapt this to produce the user and group 'bibtool'. I consider this more appropriate.

The comparison is supported since the archives are generated via a makefile. Thus the order of the files is always the same  (unless I change the makefile). Sorting is not required.

The remark about the "Debian packagaing utility" escapes my understanding

**Comment by jgmbenoit** [comment]
"I will adapt this to produce the user and group 'bibtool'. I consider this more appropriate." Do you assume that the group bibtool and the user bibtool are defined on all computers and with the same indexes ? I think it is the case for both the user root and group root which are set to zero on any UNIX box.
Sorting may help because it transcends your packaging.
Concerning your Web site. You can create the compressed tarballs (with their concomitant signature) on you box, then upload them at GitHub and certainly at CTAN, and ultimately remove them from your box. Second, have you consider to migrate from http to https ?
Concerning Debian. The upstream source ball is repacked, that is,  unnecessary material is literally remove from from the upstream tarball to gain space and sometime consistency. For example, for bibtool: the regex material, non UNiX material, autogenerated material, etc. No material can be added. I used to unpack and repack the original tarball with a very smart script of mine because there was then no Debian utility to do so. Now, such an utility exists, but it is rather rough: I guess it is a work in progress. Whatever, I migrate to this tool: Debian community overcomes.  This utility directly removes the material from the compressed tarball wrt to a list specified somewhere: in short, the type of compression remains unchanged now. Hence my request.

**Comment by ge-ne** [comment]
> Do you assume that the group bibtool and the user bibtool are defined on all computers and with the same indexes ?
In the contrary. I assume that they are **not** present. tar adapts the user to the current user when unpacking unless told otherwise. I want to avoid any security problem in the latter case.

> Concerning your Web site. You can create the compressed tarballs (with their concomitant signature) on you box, then upload them at GitHub and certainly at CTAN, and ultimately remove them from your box.
Things are a little bit more complicated. I am using a hosting service for my web pages to avoid exposing my development machines to the internet. I will think about providing more formats on GitHub...
> Second, have you consider to migrate from http to https ?
As said, things are more complicated with the hosting service. 

> in short, the type of compression remains unchanged now. 
I don't see the point. If you repackage anyhow you can choose any conpression you like.

**Comment by jgmbenoit** [comment]
in short, the type of compression remains unchanged now.
I don't see the point. If you repackage anyhow you can choose any conpression you like.

The Debian utility removes files by using tar commands (extract): no uncompression/recompression is performed.

Do you assume that the group bibtool and the user bibtool are defined on all computers and with the same indexes ?
In the contrary. I assume that they are not present. tar adapts the user to the current user when unpacking unless told otherwise. I want to avoid any security problem in the latter case.

This approach is widely used.
