### ISSUE TITLE
Sorting and keeping the keys untouched? 

### ISSUE THREAD

**Issue by np00** [ge-ne/bibtool#41]
Hello,

is it possible to sort my bib file by year (& author) and also to keep the bib keys untouched? 

This does not work:
` bibtool -- sort.format="{%d(year)%N(author)}" -S sort.cased=Off input.bib -o output.bib`

**Comment by ge-ne** [comment]
The approach goes into the right direction. sort.format is made for this purpose.
The sort.cased on the command line has to be preceded by -- to make it work and avoid the warning;-)
You might encounter  strange results in case your database has entries withour author or without year.
This is caused by your specification of the sort key. It defines a partial order only. Some cases are left to the system.
Maybe you want to use something like
  {{%d(year)#}:{%N(author)#}}
as sort format. Consult the documentation to understand what's going on here.
BTW, I prefer to avoid resources on the command line because this may end up in a shell expansion hell.

**Comment by np00** [comment]
Thanks a lot, that helped.

However, one problem I can't resolve, after consulting the documentation of course. bibtool sort unfortunately lower cases all bib keys. 

Example:
Before bibtool sort:  `@InProceedings{BOB2013]`
After bibtool sort:  `@InProceedings{bob2013]`

As far as I understood it, the key case shouldn't matter by the official documentation. Unfortunately, in my research group, it does for some members. Is there any way to preserve it?

**Comment by ge-ne** [comment]
See resource preserve.key.case
Easy, isn't it;-)

**Comment by np00** [comment]
I only tried "preserve.keys" or something similar :( Thanks a lot!
