### ISSUE TITLE
Why does lib/biblatex.rsc a field capitalization?

### ISSUE THREAD

**Issue by kiryph** [ge-ne/bibtool#46]
I am curious why bibtool capitalizes all fields in a bibfile when using the biblatex resource.

As far as I know, biblatex/biber also do not care about capitalized field or entry types.

I could imagine that this can increase readability for fields which are compounds of several words such as `indexshorttitle` (-> `IndexShortTitle`).

However, I would assume this is only personal preference and therefore wonder why this is part of the default file.

Furthermore, for the crossref mappings in the last part of the file `lib/biblatex.rsc` lowercase words are used again.

**Comment by ge-ne** [comment]
BibTeX is in fact case insensitive. The default for capitalization is my invention. BibTool knows nearly nothing about the content of bib files. Anything has to be specified in a resource. 
In fact BibTool allows to configure the appearance of the field names with the resource new.field.type and the appearance of the entry names with new.entry.type as described in the documentation and shown in lib/biblatex.rsc for instance.
I had to define a name in some way. Feel free to provide your own definition in your personal copy.

**Comment by kiryph** [comment]
Thanks for your answer.

> I had to define a name in some way.

I thought bibtool can leave them as they are in an existing bibfile. Or did I miss something?

I use my own rsc file and copied the first part of lib/biblatex.rsc so bibtool does not complain about some entry types I use which only exist in biblatex.

Thank you very much for creating and maintaining bibtool!

**Comment by ge-ne** [comment]
One goal of BibTool is to achieve a uniform notation. For this purpose any fields are normalized when reading a file (to all lower case). For printing the definition is needed to get an alternate casing.
"Leaving a field as it is" is no option since this contradicts the mission statement of BibTool.
For instance, you might find the following equivalent variants of a field name in a bib file (in different entries):

- author
- Author
- AUTHor
- AuThor
- authoR
