### ISSUE TITLE
Cases in bibtexkey output

### ISSUE THREAD

**Issue by steview2000** [ge-ne/bibtool#59]
Hi,
I just have a comment.
I use bibtool to filter my bibtex entries and it works quite well. The only annoying thing was that the output of the bibtex-key ignores the case from the bib file. 

The manual says "Some times it can be desirable to preserve the case of the key as given (even so BibTEX does not mind)." (page 27)

This is not true for my bibtex version (0.99d). Bibtex cannot find the entry with key "Examplekey" when it is specified in the latex document with \cite{examplekey}.

While this can be fixed with a bibtools resource file, I believe it would save many users some time if "preserve.key.case = on" would be set by default.

Cheers!

**Comment by ge-ne** [comment]
I have just tried to reproduce the BibTeX problem with BibTeX 0.99d from TeXLive. I can not confirm that BibTeX treats the key case-sensitive. Note the sequence latex -> bibtex -> latex -> latex is required to get the entries included and resolved.

**Comment by steview2000** [comment]
Hmm, that is strange. I just tried a minimal example:
test.tex:

```
\documentclass{article}
\begin{document}
Testcitation: \cite{ABPCS05}
Testcitation: \cite{abpcs05}
\bibliographystyle{unsrt}       
\bibliography{test}   
\end{document}
```

and a test.bib:
```
@Article{ABPCS05,
  Title                    = {The Kuramoto model: A simple paradigm for synchronization phenomena},
  Author                   = {Acebr\'on, Juan A. and Bonilla, L. L. and P\'erez Vicente, Conrad J. and Ritort, F\'elix and Spigler, Renato},
  Journal                  = {Rev. Mod. Phys.},
  Year                     = {2005},
  Month                    = {Apr},
  Pages                    = {137--185},
  Volume                   = {77},
  Doi                      = {10.1103/RevModPhys.77.137},
  Issue                    = {1},
  Numpages                 = {0},
  Publisher                = {American Physical Society}
}
```

The first \cite{ABPCS05} was compiled without a problem. For the secodn \cite{abpcs05} I got the following error: 
Case mismatch error between cite keys abpcs05 and ABPCS05
---line 3 of file test.aux
 : \citation{abpcs05
 :                  }
I'm skipping whatever remains of this command

**Comment by ge-ne** [comment]
I do not get an error. Maybe caused by an old TeXLive installation used by me.

I can reproduce that the second \cite is not resolved.
Nevertheless this is not caused by BibTeX. BibTeX produces a bbl file containing exactly one entry. BibTeX does not report that something could not be resolved. The key of the \bibitem uses the first key found.

To me it appears to be a problem of the implementation of \cite. Since the resolution of references makes use of TeX macros the case matters on this level. That's what you seen in your error message

As a consequence I would conclude that it is a bad idea to use keys which differ in case only in one LaTeX file...
