### ISSUE TITLE
fmt.word.separator is not working

### ISSUE THREAD

**Issue by adouzzy** [ge-ne/bibtool#9]
I use bibtool to generate new cite keys with following argument:
 -f '%-1w(author)%4d(year)%-1W(title)' 
In ~/.bibtoolsrc I have :
fmt.word.separator = "+-<=>*/"

But the key generated is  
author2000abc-def
I want to make - as the separator and have just the key author2000abc.

The original bib record is in form of 
title = "The abc-def of  blablabla. "

Could please help?
Thanks

**Comment by ge-ne** [comment]
fmt.word.separator is a string insered when formatting -- thus the name. The definition of word includes - as legal character to constitute a single word. Thus the behaviour of BibTool is as expected.

This request can no be solved with BibTool as is. If you are adventerous you can change the classification of - in type.h and recompile a private version of BibTool.
Since the fiddling around with the classification is error-prone  I don't want to provide a command to do so.
